---
- name: Perform user management as root
  block:
    - name: Remove user
      user:
        name: "{{ item }}"
        state: absent
      with_items: "{{ mattjmcnaughton_rasp_pi_cleanup_users_to_remove }}"
  become: yes
