---
# Provision home-assistant on rasp-pi
#
# Run w/ the following:
# `ansible-playbook -K home-assistant.yml`
#
# Currently, we access the web ui by opening 443 on the firewall,
# and can access home-assistant via `https://IP`.
# We still need to solve internal DNS,
# but in the short term, we can hack that with `/etc/hosts`
# updates.
- hosts: home-assistant
  tasks:
    - include_role:
        name: mattjmcnaughton.rasp-pi-base
      vars:
        mattjmcnaughton_rasp_pi_base_username: "mattjmcnaughton"
        mattjmcnaughton_rasp_pi_base_ufw_incoming_ports_to_allow:
          - "22"
          - "80"
          - "443"
          - "1883"  # Need to allow traffic to mqtt broker
    - include_role:
        name: mattjmcnaughton.home-assistant
      vars:
        # `/opt/fs` is created by our rasp-pi-from-scratch-init.yml playbook.
        # Long term, we may want to have this directory on an NFS share or ...
        mattjmcnaughton_home_assistant_host_data_dir: /opt/fs/homeassistant

    # We leave adding the `mattjmcnaughton.io` certs as a separate playbook
    # via the `rasp-pi-copy-ssl-certs.yml` playbook.
    - debug:
        msg: "If this machine is newly provisioned, please run the `rasp-pi-copy-ssl-certs.yml` playbook."
