---
- name: Execute zfs actions as root
  block:
    - name: Gather facts around the specific zpool we're managing
      zpool_facts:
        name: "{{ item.pool }}"
      register: zpool_facts
      # Task will fail if the zpool doesn't exist.
      ignore_errors: true

    - name: Determine if should create zpool
      set_fact:
        should_create_zpool: zpool_facts.failed == true

    - name: Create zpool
      # Need the `-f` when using w/ Rasp Pi. Eitherwise we got warnings around
      # the disk being part of a potentially active pool.
      command: "zpool create -f {{ item.pool }} {{ item.vdevs | join(' ') }}"
      when: should_create_zpool

    - name: Create datasets
      include_tasks: "dataset.yml"
      with_items: "{{ item.datasets }}"
  become: yes
