" don't bother with vi compatibility
set nocompatible

" enable syntax highlighting
syntax enable

" ensure ftdetect et al work by including this after the Vundle stuff
filetype plugin indent on

set autoindent
set autoread                                                 " reload files when changed on disk, i.e. via `git checkout`
set backspace=2                                              " Fix broken backspace in some setups
set clipboard=unnamed                                        " yank and paste with the system clipboard
set encoding=utf-8
set expandtab                                                " expand tabs to spaces
set ignorecase                                               " case-insensitive search
set incsearch                                                " search as you type
set laststatus=2                                             " always show statusline
set list                                                     " show trailing whitespace
set listchars=tab:▸\ ,trail:▫
set number                                                   " show line numbers
set ruler                                                    " show where you are
set scrolloff=3                                              " show context above/below cursorline
set shiftwidth=2                                             " normal mode indentation commands use 2 spaces
set showcmd
set smartcase                                                " case-sensitive search if any caps
set softtabstop=2                                            " insert mode tab and backspace use 2 spaces
set tabstop=8                                                " actual tabs occupy 8 characters
set tildeop                                                  " use ~ as operator (for caps)
set wildignore=log/**,node_modules/**,target/**,tmp/**,*.rbc
set wildmenu                                                 " show a navigable menu for tab completion
set wildmode=longest,list,full

" Enable basic mouse behavior such as resizing buffers.
set mouse=a
if exists('$TMUX')  " Support resizing in tmux
  set ttymouse=xterm2
endif

" keyboard shortcuts
let mapleader = ','
noremap <C-h> <C-w>h
noremap <C-j> <C-w>j
noremap <C-k> <C-w>k
noremap <C-l> <C-w>l
noremap <leader>l :Align
nnoremap <leader><space> :call whitespace#strip_trailing()<CR>

" automatically rebalance windows on vim resize
autocmd VimResized * :wincmd =

" Fix Cursor in TMUX
if exists('$TMUX')
  let &t_SI = "\<Esc>Ptmux;\<Esc>\<Esc>]50;CursorShape=1\x7\<Esc>\\"
  let &t_EI = "\<Esc>Ptmux;\<Esc>\<Esc>]50;CursorShape=0\x7\<Esc>\\"
else
  let &t_SI = "\<Esc>]50;CursorShape=1\x7"
  let &t_EI = "\<Esc>]50;CursorShape=0\x7"
endif

" Don't copy the contents of an overwritten selection.
vnoremap p "_dP

" Set textwidth at 80
set textwidth=80
set tabstop=2

" Escape parens, brakcets, quotes... w/ ctrl-k
inoremap <C-k> <Esc>/[)}"'\]>]<CR>:nohl<CR>a

" Automatically close
inoremap {      {}<Left>
inoremap {<CR>  {<CR>}<Esc>O
inoremap {{     {
inoremap {}     {}

inoremap (      ()<Left>
inoremap (<CR>  (<CR>)<Esc>O
inoremap ((     (
inoremap ()     ()

inoremap [      []<Left>
inoremap [<CR>  [<CR>]<Esc>O
inoremap [[     [
inoremap []     []

" Git
autocmd Filetype gitcommit setlocal spell textwidth=72

" Filetype indendation configuration
autocmd Filetype php setlocal ts=4 sts=4 sw=4
autocmd Filetype go setlocal ts=8 sts=8 sw=8 nolist
autocmd Filetype python setlocal ts=4 sts=4 sw=4
autocmd Filetype c setlocal ts=4 sts=4 sw=4
autocmd Filetype java setlocal ts=4 sts=4 sw=4
autocmd Filetype sh setlocal ts=2 sts=2 sw=2
autocmd Bufread,BufNewFile *.rs setlocal ts=4 sts=4 sw=4

" Spellchecking for txt and md and json
autocmd BufRead,BufNewFile *.md set spell
autocmd Bufread,BufNewFile *.md setlocal spell
autocmd Bufread,BufNewFile *.txt setlocal spell
autocmd Bufread,BufNewFile *.tex setlocal spell
autocmd Bufread,BufNewFile *.json setlocal nospell

" Properly configure file types when extensions (such as `.j2` or `.erb`)
" confuse Vim.
autocmd Bufread,BufNewFile *.sh.* setfiletype sh
autocmd BufRead,BufNewFile *.md set filetype=markdown

" Set maxmempattern to a higher value to avoid `pattern uses more memory than
" 'maxmempattern' error.
set maxmempattern=10000
