galaxy_info:
  author: mattjmcnaughton
  description: From scratch init provisioning for the Rasp Pi.

  license: Apache

  min_ansible_version: 2.4

  platforms:
  - name: Ubuntu
    versions:
    - 20.04
