---
- name: restart mosquitto
  ansible.builtin.service:
    name: mosquitto
    state: restarted
  listen: "restart mosquitto"
  become: yes

- name: reload mosquitto
  ansible.builtin.service:
    name: mosquitto
    state: reloaded
  listen: "reload mosquitto"
  become: yes
