---
- name: Create mosquitto passwd file
  ansible.builtin.template:
    src: mosquitto.passwd.j2
    dest: "{{ mattjmcnaughton_mqtt_mosquitto_passwd_path }}"
    owner: root
    group: root
    mode: "0644"
  notify: reload mosquitto
  no_log: True
  become: yes
