galaxy_info:
  author: mattjmcnaughton
  description: Clean up raspberry pi after running from scratch provisioning.

  license: Apache

  min_ansible_version: 2.4

  platforms:
  - name: Ubuntu
    versions:
    - 20.04
